# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06489bb6f86548d33bcca2999b7f9f4f8c5e035babdc9643c7d473d156d5120e80c5711c1df8d3713b9c7d7951b10b01c4d2cb5b94034767ebb25709e53d457a

test:
  secret_key_base: fbe6c8d0f35c7e85d8007c0a928b4717639825b4291a7931e1ed4587f0cdd434be4e7710501652942c6e9883f3f999f0483b035fe23d47e25542b0b76f452f7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
